[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = { workspace = true }
dioxus = { workspace = true, features = ["router", "fullstack"] }
ui = { workspace = true }

[features]
default = []
desktop = ["dioxus/desktop"]
server = ["dioxus/server", "ui/server"]
