[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
boilermaker_core = { workspace = true }
color-eyre = { workspace = true }
dioxus = { workspace = true, features = ["router", "fullstack"] }
once_cell = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
ui = { workspace = true }

[features]
default = []
desktop = ["dioxus/desktop"]
server = ["dioxus/server", "ui/server"]
