[project]
name = "hello-world"
description = "A simple hello world example using Boilermaker"
default_lang = "rust"
repository = "https://github.com/yeajustmars/boilermaker"
subdir = "examples/hello-world"
version = "0.1.0"
authors = ["yeajustmars <yeajustmars@gmail.com>"]
keywords = ["boilermaker", "example"]
website = "https://boilermaker.dev/templates/hello-world"
license = "MIT"

[variables]
welcome_message = "Hello, World!"
