[application]
name = "Boilermaker Desktop"
icon = "assets/logo-flame.png"
#tailwind_input = "tailwind.css"
#tailwind_output = "assets/tailwind.css"

[bundle.macos]
# macOS specific options

[bundle.linux]
# Linux specific options
