[package]
name = "boilermaker_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
boilermaker_core = { workspace = true }
clap = { workspace = true }
color-eyre = { workspace = true }
colored = { workspace = true }      # TODO: pick one of colored or nu-ansi-term
dirs = { workspace = true }
fs_extra = { workspace = true }
git2 = { workspace = true }
lazy_static = { workspace = true }
#nu-ansi-term = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
tabled = { workspace = true }
# TODO: remove tokio full feature and only enable the features needed
tokio = { workspace = true, features = ["full"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-error = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
walkdir = { workspace = true }

[[bin]]
name = "boil"
path = "src/main.rs"
